version: "3"

services:
    api:
        image: epicsoftware/epic-pos-api
        command: npm start
        environment:
            - MONGODB_URI=mongodb://db/epic-pos
        ports: 
            - "3443:3443"
        networks: 
            - epic-pos-bridge
        links: 
            - db
    web:
        image: epicsoftware/epic-pos-web
        command: npm start
        ports:
            - "3333:3333"
        networks: 
            - epic-pos-bridge
        environment: 
            - BASE_URL=http://0.0.0.0:3333
            
    db:
        image: mongo
        container_name: db
        networks: 
            - epic-pos-bridge    


networks:
    epic-pos-bridge:  
